dist: trusty
sudo: false
language: python
python:
  - "3.6"
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo apt-get update -q
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get --purge -y remove postgresql
install:
  - sudo apt-get install redis-server postgresql-10 -y
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart
  - pip install -e .
  - pip install -e .[test]
script: pytest
after_success:
  - codecov
  - sudo apt-get install nodejs npm -y
  - npm i -g shins widdershins
  - widdershins --omitBody --resolve spec/restapi.yml source/index.html.md
  - shins --minify --inline
  - mkdir shins
  - mv index.html shins
before_deploy:
  - zip -r latest *
  - mkdir -p aws_upload
  - mv latest.zip aws_upload/latest.zip
deploy:
- provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  allow-empty-commit: true
  verbose: true
  local_dir: shins
  on:
    branch: master
- provider: s3
  access_key_id: AKIAIQZ6VQOFSEMUSNYQ
  secret_access_key:
    secure: "Rw8YVfDcg1KWAjXntudY/swOZtmsApIpuJBQ2MzbyujkQAAeUgQL//iJ4IQ5qtzwc5IYQW/BFEo7N/m97FFeLloAQS+9IkxxEQDhxdWynlJiaSx1GolRSgfWUEPo06tbDviG/tghSlfw8WA/tazRqNdT71UyIdFwxxdaA2goQWYJaJaGN4xDee6GCwXiC4AnUsldBwmRADRyS9k4xEm/lMED3bvR9z8GZfytSoDfZex976u3uev3v/eEzfBpYuSnpSoLwYzwyj+wp6kuZaCJLtlgAsqqpGSqXEPSOxjErjAhK4Lawb8dB327jrkPuSxb1SFVscsH1Y+KkXEhYGB5QVCkHg6tfjPLpQboO0pePQ1zxqGO566r34D9UTPoWtsd6Z2cW6Fq8rncsKW+Jwxupsotq6xadwQJp2XkJBOKgfR4HbWYcRbyYh19kI9PN4Urp7STbvyYbX58+kmA7auVuiVyPrg0hLPVW+LVzV36Bl5EoBY7whNA0gMPp6yduKF81nV9QrfiaVnXkIwHhdEjTPGskpNeHGvqv2nWsQkU5HbID5O90rQbFUl+AqAW89hjg0SnlOJnW/JJT8lJiCIKPAnC9tTITRi2lhpsjB/AgGq9gJII5eyuKnThP69tBCm9e7SlXQ6byg2nf+F+JlD77uWyYk3QvXIGEWXa7gPDTpQ="
  bucket: cloud-player-api
  region: eu-central-1
  local_dir: aws_upload
  skip_cleanup: true
  on:
    branch: production
- provider: codedeploy
  access_key_id: AKIAIQZ6VQOFSEMUSNYQ
  secret_access_key:
    secure: "Rw8YVfDcg1KWAjXntudY/swOZtmsApIpuJBQ2MzbyujkQAAeUgQL//iJ4IQ5qtzwc5IYQW/BFEo7N/m97FFeLloAQS+9IkxxEQDhxdWynlJiaSx1GolRSgfWUEPo06tbDviG/tghSlfw8WA/tazRqNdT71UyIdFwxxdaA2goQWYJaJaGN4xDee6GCwXiC4AnUsldBwmRADRyS9k4xEm/lMED3bvR9z8GZfytSoDfZex976u3uev3v/eEzfBpYuSnpSoLwYzwyj+wp6kuZaCJLtlgAsqqpGSqXEPSOxjErjAhK4Lawb8dB327jrkPuSxb1SFVscsH1Y+KkXEhYGB5QVCkHg6tfjPLpQboO0pePQ1zxqGO566r34D9UTPoWtsd6Z2cW6Fq8rncsKW+Jwxupsotq6xadwQJp2XkJBOKgfR4HbWYcRbyYh19kI9PN4Urp7STbvyYbX58+kmA7auVuiVyPrg0hLPVW+LVzV36Bl5EoBY7whNA0gMPp6yduKF81nV9QrfiaVnXkIwHhdEjTPGskpNeHGvqv2nWsQkU5HbID5O90rQbFUl+AqAW89hjg0SnlOJnW/JJT8lJiCIKPAnC9tTITRi2lhpsjB/AgGq9gJII5eyuKnThP69tBCm9e7SlXQ6byg2nf+F+JlD77uWyYk3QvXIGEWXa7gPDTpQ="
  deployment_group: DeployGroupCp
  region: eu-central-1
  bucket: cloud-player-api
  key: latest.zip
  bundle_type: zip
  application: ApiCp
  skip_cleanup: true
  on:
    branch: production
