version: 0.0
os: linux
files:
  - source: .
    destination: /var/www
  - source: ./supervisord.conf
    destination: /etc/supervisor/conf.d/api.conf
permissions:
  - object: /var/www/api
    owner: www-data
    group: www-data
    type:
      - directory
      - file
  - object: /etc/supervisor/conf.d/api.conf
    owner: root
    group: root
    type:
      - file
hooks:
 BeforeInstall:
   - location: scripts/install-as-root.sh
     timeout: 300
     runas: root
 AfterInstall:
   - location: scripts/install-as-user.sh
     timeout: 600
     runas: www-data
 ApplicationStart:
   - location: scripts/run.sh
     timeout: 120
     runas: root
 ApplicationStop:
   - location: scripts/stop.sh
     timeout: 120
     runas: root
 ValidateService:
   - location: scripts/validate.sh
     timeout: 60
     runas: root
