version: 0.1
os: linux
files:
  - source: .
    destination: /srv/cloudplayer
  - source: ./api.conf
    destination: /etc/supervisor/conf.d
  - source: ./cloudplayer.conf
    destination: /etc/nginx/sites-enabled
permissions:
  - object: /srv/cloudplayer
    owner: cloudplayer
    group: cloudplayer
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: scripts/install-as-root.sh
      timeout: 300
      runas: root
    - location: scripts/install-as-user.sh
      timeout: 600
      runas: cloudplayer
    - location: scripts/init-database.sh
      timeout: 100
      runas: postgres
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
