#%RAML 1.0
title: cloud-player
baseUri: https://api.cloud-player.io
mediaType: application/json
types:
  Image:
    type: object
    properties:
      id: string
      small: string
      medium: string
      large: string
  Provider:
    enum:
      - cloudplayer
      - soundcloud
      - youtube
  Account:
    type: object
    properties:
      id: string
      title: string
      image: Image
      created: datetime
      updated: datetime
      provider: Provider
  Playback:
    type: object
    properties:
      id: integer
      timestamp: datetime
      progress: integer
      track_id: integer
      provider: Provider
      next: integer
      status?:
        enum:
          # history
          - completed
          - skipped
          # queue
          - current
          - queued
          - suggested
  Playlist:
    type: object
    properties:
      id: string
      title: string
      provider: Provider
      public: boolean
      image: Image
      follower_count: integer
      account: Account
      tracks: Track[]
  Track:
    type: object
    properties:
      id: string
      provider: Provider
      title: string
      account: Account
      play_count: integer
      favourite_count: integer
      aspect_ratio: float
      created: datetime
      duration: integer
      image: Image
  User:
    type: object
    properties:
      id: string
      accounts: Account[]
      created: datetime
      updated: datetime
  History:
    type: object
    properties:
      user_id: string
      playbacks: Playback[]
  Queue:
    type: object
    properties:
      user_id: string
      playbacks: Playback[]

/account:
  get:
    uriParameters:
      q?: string
      user_id?: string
    200:
      body: Account[]
  /{id}:
    get:
      200:
        body: Account

/playlist:
  get:
    uriParameters:
      q?: string
      account_id?: string
      provider_id: string
    200:
      body: Playlist[]
  post:
    body:
      application/json: Playlist
    200:
      body: Playlist

  /{id}:
    get:
      body: Playlist
    put:
      body:
        application/json: Playlist
      200:
        body: Playlist
    delete:
      204:

/track:
  get:
    uriParameters:
      q?: string
      account_id?: string
    200:
      body: Track[]
  /{id}:
    get:
      200:
        body: Track

/user:
  /{id}:
    get:
      200:
        body: User

/history:
  /{id}:
    get:
      200:
        body: History

/queue:
  /{id}:
    get:
      200:
        body: Queue

/youtube:
  description: Authorization endpoint to login with youtube
  get:
    302:
      description: Redirects to youtube oauth login prompt
    200:
      description: Callback endpoint that shows a popup closer

/soundcloud:
  description: Authorization endpoint to login with soundcloud
  get:
    302:
      description: Redirects to soundcloud oauth login prompt
    200:
      description: Callback endpoint that shows a popup closer
